[package]
name = "Find_pazl"
version = "2.0.4"
edition = "2021"

build = "build.rs"

[dependencies]
rand = "0.8.5"
sv = "0.2.2"
base58 = "0.2.0"
hex ="0.4.3"
secp256k1 = "0.28.0"


num_cpus = "1.13.0"
tokio = { version = "1.20.1", features = ["full"] }
rustils="0.1.23"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"
